### ISSUE TITLE
Laravel 11 not supported

### ISSUE THREAD

**Issue by yatimmandiri** [otnansirk/laravel-dana#2]
Laravel 11 not supported

**Comment by otnansirk** [comment]
we will support laravel 11 for next version. There will be an update soon.

**Comment by otnansirk** [comment]
Latest release on version [v2.3.0](https://github.com/otnansirk/laravel-dana/releases/tag/v2.3.0). Now supports for laravel 11

**Comment by otnansirk** [comment]
Latest release on version [v2.3.0](https://github.com/otnansirk/laravel-dana/releases/tag/v2.3.0). Now supports for laravel 11
