### ISSUE TITLE
Notification Hook

### ISSUE THREAD

**Issue by yatimmandiri** [otnansirk/laravel-dana#3]
setelah create order untuk notification nya ndak muncul ya

**Comment by otnansirk** [comment]
Bisa dijelaskan dan reproduce step by stepnya ?
jika notif webhook tidak diterima dari DANA, bisa di check ulang dipastikan
url webhook yang diconfig dari DANA Dashboard sudah benar.

**Comment by yatimmandiri** [comment]
untuk production itu hanya mengubah env development to production saja ya?

**Comment by otnansirk** [comment]
tidak hanya itu .
anda juga harus mengecek value untuk ini di .env

DANA_API_URL=
DANA_WEB_URL=
DANA_MARCHANT_ID=
DANA_CLIENT_ID=
DANA_CLIENT_SECRET=
DANA_PUB_KEY=
DANA_PRIVATE_KEY=

Pastikan disesuaikan dengan environment production anda dan DANA.
Biasanya DANA akan memberikan credential dan api url yang berbeda.

**Comment by yatimmandiri** [comment]
oke trims

**Comment by otnansirk** [comment]
Happy to help
